// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZx9NVJoTSZvDnDvJHpsDQy0k_EpOFDE',
    appId: '1:635822746544:web:cce64244734e187f96c475',
    messagingSenderId: '635822746544',
    projectId: 'chat-app-61663',
    authDomain: 'chat-app-61663.firebaseapp.com',
    storageBucket: 'chat-app-61663.appspot.com',
    measurementId: 'G-TTKYTMZG22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZM_xQMXQah23rVU4MtbSsUxuQjHl0C0',
    appId: '1:635822746544:android:efa3c931b792d16396c475',
    messagingSenderId: '635822746544',
    projectId: 'chat-app-61663',
    storageBucket: 'chat-app-61663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIuHNGCAT_mMM35tBtlj2D5LtECQFktbw',
    appId: '1:635822746544:ios:73c177998071e79296c475',
    messagingSenderId: '635822746544',
    projectId: 'chat-app-61663',
    storageBucket: 'chat-app-61663.appspot.com',
    iosClientId: '635822746544-baium45gbe8338qin30uv2du0sopt4oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIuHNGCAT_mMM35tBtlj2D5LtECQFktbw',
    appId: '1:635822746544:ios:73c177998071e79296c475',
    messagingSenderId: '635822746544',
    projectId: 'chat-app-61663',
    storageBucket: 'chat-app-61663.appspot.com',
    iosClientId: '635822746544-baium45gbe8338qin30uv2du0sopt4oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
